/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1;

import static com.mycompany.proyecto1.AppState.listaregiones;
import java.awt.event.ItemEvent;
import java.util.Random;
import javax.swing.*;

/**
 *
 * @author josse
 */
public class DeptosMuniFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeptosMuniFrame
     */
    public DeptosMuniFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("MANEJO DE DEPARTAMENTOS Y MUNICIPIOS");
        
       
        
        for(int i = 0; i < listaregiones.size(); i++) {
        regionCombo.addItem(listaregiones.get(i).getCodigoR().toString());   
        }
        
        
       
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        regionCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        deptosCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        codigodeptoTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        municipioTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codigoR = new javax.swing.JTextField();
        nombreR = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombreMod = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manejo de Departamentos y Municipios");

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setText("REGRESAR AL MENÚ");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Código/Nombre de Región");

        regionCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                regionComboItemStateChanged(evt);
            }
        });
        regionCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regionComboMouseClicked(evt);
            }
        });
        regionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Departamento");

        deptosCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deptosComboItemStateChanged(evt);
            }
        });
        deptosCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptosComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Código de Departamento");

        codigodeptoTxt.setEditable(false);
        codigodeptoTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel5.setText("Municipio");

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setText("APERTURAR MUNICIPIO");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Modificar y Eliminar");

        jLabel7.setText("Código de Departamento");

        jLabel8.setText("Nombre Actual del Municipio");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Datos Relacionado");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("Datos a Modificar");

        jLabel11.setText("Nuevo Nombre del Municipio");

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("MODIFICAR DATOS");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("ELIMINAR MUNICIPIO");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deptosCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(regionCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(municipioTxt)
                            .addComponent(jLabel4)
                            .addComponent(codigodeptoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoR)
                    .addComponent(jLabel8)
                    .addComponent(nombreR)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(nombreMod)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(regionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(municipioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deptosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigodeptoTxt)))
                        .addGap(38, 38, 38)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         MenuAdminFrame menua = new  MenuAdminFrame();
        menua.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regionComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_regionComboItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()== ItemEvent.SELECTED){ 
            if(this.regionCombo.getSelectedIndex()==0){ 
                this.deptosCombo.setModel(new DefaultComboBoxModel(this.getMetropolitana(this.regionCombo.getSelectedItem().toString())));
            }else if(this.regionCombo.getSelectedIndex()==1){ 
                this.deptosCombo.setModel(new DefaultComboBoxModel(this.getNorte(this.regionCombo.getSelectedItem().toString())));
            }else if(this.regionCombo.getSelectedIndex()==2){ 
                this.deptosCombo.setModel(new DefaultComboBoxModel(this.getNororiente(this.regionCombo.getSelectedItem().toString())));
            }else if(this.regionCombo.getSelectedIndex()==3){ 
                this.deptosCombo.setModel(new DefaultComboBoxModel(this.getSuroriente(this.regionCombo.getSelectedItem().toString())));
            }else if(this.regionCombo.getSelectedIndex()==4){ 
                this.deptosCombo.setModel(new DefaultComboBoxModel(this.getNoroccidente(this.regionCombo.getSelectedItem().toString())));
            }else if(this.regionCombo.getSelectedIndex()==5){ 
                this.deptosCombo.setModel(new DefaultComboBoxModel(this.getSuroccidente(this.regionCombo.getSelectedItem().toString())));
            }
        }
        if(evt.getStateChange()== ItemEvent.SELECTED){ 
            if(this.deptosCombo.getSelectedItem().toString().equals("Guatemala")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("G-TML");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Baja Verapaz")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("B-JVP");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Chiquimula")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("C-MLA");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Jutiapa")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("J-TPA");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Huehuetenango")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("H-TNG");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Quetzaltenango")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("Q-ZTG");
            }
        }
    }//GEN-LAST:event_regionComboItemStateChanged

    private void deptosComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptosComboActionPerformed
            // TODO add your handling code here:
            if(this.deptosCombo.getSelectedItem().toString().equals("Guatemala")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("G-TML");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Escuintla")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("E-CTL");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Chimaltenango")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("C-MTG");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Sacatepéquez")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("S-CPZ");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Baja Verapaz")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("B-JVP");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Alta Verapaz")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("A-VPZ");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Petén")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("P-TEN");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Chiquimula")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("C-MLA");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("El Progreso")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("E-PRS");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Izabal")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("I-ZBL");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Zacapa")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("Z-CPA");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Jutiapa")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("J-TPA");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Jalapa")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("J-LPA");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Santa Rosa")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("S-RSA");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Huehuetenango")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("H-TNG");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Quiché")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("Q-CHE");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Quetzaltenango")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("Q-ZTG");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Retalhuleu")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("R-TLU");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("San Marcos")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("S-MRC");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Suchitepéquez")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("S-TPZ");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Sololá")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("S-OLA");
            }
            else if(this.deptosCombo.getSelectedItem().toString().equals("Totonicapán")){
                this.codigodeptoTxt.setText(null);
                this.codigodeptoTxt.setText("T-NCP");
            }
            
            
       
    }//GEN-LAST:event_deptosComboActionPerformed

    private void regionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_regionComboActionPerformed

    private void regionComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regionComboMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_regionComboMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String departamento1= deptosCombo.getSelectedItem().toString();
         String region= regionCombo.getSelectedItem().toString();
        String municipio1 = municipioTxt.getText();
        String codigodepto = codigodeptoTxt.getText();
        Sucursales addsucursal= new Sucursales();
        
        if(municipioTxt.getText().isEmpty()|| deptosCombo.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        }
        else{
            int counterror=0;
            for (int k=0;k<AppState.listasucursales.size();k++){
                if (municipio1.equals(AppState.listasucursales.get(k).getMunicipio())==true){      
                    JOptionPane.showMessageDialog(null, "Este municipio ya se encuentra disponible", "Municipio Existente", JOptionPane.WARNING_MESSAGE); 
                    counterror++;
                    break;
                }
            }
            if (counterror==0){
            addsucursal.setCodigoReg(region);
            addsucursal.setDepartamento(departamento1);
            addsucursal.setCodigoDepto(codigodepto);
            addsucursal.setMunicipio(municipio1);
            AppState.listasucursales.add(addsucursal);
                for(int i = 0; i< AppState.listasucursales.size(); i++){ 
                    System.out.println(AppState.listasucursales.get(i).getCodigoReg()+"-"+AppState.listasucursales.get(i).getDepartamento()+"-"+AppState.listasucursales.get(i).getCodigoDepto()+"-"+AppState.listasucursales.get(i).getMunicipio());   
                }
                JOptionPane.showMessageDialog(null, "Ubicación Aperturada Correctamente", "Manejo de Departamentos y Municipios", JOptionPane.INFORMATION_MESSAGE);
                municipioTxt.setText(null);
               
                   
                
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deptosComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deptosComboItemStateChanged
        // TODO add your handling code here:
       
      
    }//GEN-LAST:event_deptosComboItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(codigoR.getText().isEmpty() || nombreR.getText().isEmpty() || nombreMod.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        }else{
            String codigo = codigoR.getText();
            String nombre = nombreR.getText();
            String nuevonombre = nombreMod.getText();
            boolean validar = false;
            for (int k=0;k<AppState.listasucursales.size();k++){
                if (codigo.equals(AppState.listasucursales.get(k).getCodigoDepto())==true && nombre.equals(AppState.listasucursales.get(k).getMunicipio())==true){      
                   validar = true;
                   break;
                }else {
                    validar = false;
                }     
           }
            if (validar) {
                for (int k=0;k<AppState.listasucursales.size();k++){
                        if (codigo.equals(AppState.listasucursales.get(k).getCodigoDepto())==true && nombre.equals(AppState.listasucursales.get(k).getMunicipio())==true){      
                            AppState.listasucursales.get(k).setMunicipio(nuevonombre);
                             for(int i = 0; i< AppState.listasucursales.size(); i++){ 
                                System.out.println(AppState.listasucursales.get(i).getCodigoReg()+"-"+AppState.listasucursales.get(i).getDepartamento()+"-"+AppState.listasucursales.get(i).getCodigoDepto()+"-"+AppState.listasucursales.get(i).getMunicipio());   
                            }
                        }
                    }
                     JOptionPane.showMessageDialog(null, "Municipio actualizado correctamente", "Administrar Deptos. y Municipios", JOptionPane.INFORMATION_MESSAGE); 
                     codigoR.setText(null); nombreR.setText(null); nombreMod.setText(null);
            }else {  
               JOptionPane.showMessageDialog(null, "Los datos no coinciden", "Administrar Deptos. y Municipios", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(codigoR.getText().isEmpty() || nombreR.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        }else{
            String codigo = codigoR.getText();
            String nombre = nombreR.getText();
            String nuevonombre = nombreMod.getText();
            boolean validar = false;
            for (int k=0;k<AppState.listasucursales.size();k++){
                if (codigo.equals(AppState.listasucursales.get(k).getCodigoDepto())==true && nombre.equals(AppState.listasucursales.get(k).getMunicipio())==true){      
                   validar = true;
                   break;
                }else {
                    validar = false;
                }     
           }
            if (validar) {
                for (int k=0;k<AppState.listasucursales.size();k++){
                        if (codigo.equals(AppState.listasucursales.get(k).getCodigoDepto())==true && nombre.equals(AppState.listasucursales.get(k).getMunicipio())==true){      
                            AppState.listasucursales.remove(k);
                             for(int i = 0; i< AppState.listasucursales.size(); i++){ 
                                System.out.println(AppState.listasucursales.get(i).getCodigoReg()+"-"+AppState.listasucursales.get(i).getDepartamento()+"-"+AppState.listasucursales.get(i).getCodigoDepto()+"-"+AppState.listasucursales.get(i).getMunicipio());   
                            }
                        }
                    }
                     JOptionPane.showMessageDialog(null, "Municipio eliminado correctamente", "Administrar Deptos. y Municipios", JOptionPane.INFORMATION_MESSAGE); 
                     codigoR.setText(null); nombreR.setText(null); nombreMod.setText(null);
            }else {  
               JOptionPane.showMessageDialog(null, "Los datos no coinciden", "Administrar Deptos. y Municipios", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /*    */
    public String[] getMetropolitana(String region1){ 
        String[] listadepartamentos1 = new String[4];
        if(region1.equalsIgnoreCase("(M) Metropolitana")){
            listadepartamentos1[0]="Guatemala";
            listadepartamentos1[1]="Escuintla";
            listadepartamentos1[2]="Chimaltenango";
            listadepartamentos1[3]="Sacatepéquez";
        }
        return listadepartamentos1;
    }
    public String[] getNorte(String region2){ 
        String[] listadepartamentos2 = new String[3];
        if(region2.equalsIgnoreCase("(NT) Norte")){
            listadepartamentos2[0]="Baja Verapaz";
            listadepartamentos2[1]="Alta Verapaz";
            listadepartamentos2[2]="Petén";
        }
        return listadepartamentos2;
    }
    public String[] getNororiente(String region3){ 
        String[] listadepartamentos3 = new String[4];
        if(region3.equalsIgnoreCase("(NO) Nororiente")){
             listadepartamentos3[0]="Chiquimula";
             listadepartamentos3[1]="El Progreso";
             listadepartamentos3[2]="Izabal";
             listadepartamentos3[3]="Zacapa";
        }
        return listadepartamentos3;
    }
    public String[] getSuroriente(String region4){ 
        String[] listadepartamentos4 = new String[3];
        if(region4.equalsIgnoreCase("(SO) Suroriente")){
              listadepartamentos4[0]="Jutiapa";
             listadepartamentos4[1]="Jalapa";
             listadepartamentos4[2]="Santa Rosa";
        }
        return listadepartamentos4;
    }
    public String[] getNoroccidente(String region5){ 
        String[] listadepartamentos5 = new String[2];
        if(region5.equalsIgnoreCase("(NOC) Noroccidente")){
            listadepartamentos5[0]="Huehuetenango";
            listadepartamentos5[1]="Quiché";
             
        }
        return listadepartamentos5;
    }
    public String[] getSuroccidente(String region6){ 
        String[] listadepartamentos6 = new String[6];
        if(region6.equalsIgnoreCase("(SOC) Suroccidente")){
             listadepartamentos6[0]="Quetzaltenango";
             listadepartamentos6[1]="Retalhuleu";
             listadepartamentos6[2]="San Marcos";
             listadepartamentos6[3]="Suchitepéquez";
             listadepartamentos6[4]="Sololá";
             listadepartamentos6[5]="Totonicapán";
        }
        return listadepartamentos6;
    }
   
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeptosMuniFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeptosMuniFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeptosMuniFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeptosMuniFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeptosMuniFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoR;
    private javax.swing.JTextField codigodeptoTxt;
    private javax.swing.JComboBox<String> deptosCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField municipioTxt;
    private javax.swing.JTextField nombreMod;
    private javax.swing.JTextField nombreR;
    private javax.swing.JComboBox<String> regionCombo;
    // End of variables declaration//GEN-END:variables
}
