/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1;

import static com.mycompany.proyecto1.AppState.listaregiones;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.io.File;
import javax.swing.*;


/**
 *
 * @author josse
 */
public class RegistroFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistroFrame
     */
    public RegistroFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("REGISTRO DE USUARIOS");
        
        rutaTxt.setVisible(false);
        
        kioskosCombo.setVisible(false);
        kioskoLbl.setVisible(false);
        for(int i = 0; i < AppState.listakioskos.size(); i++) {
        kioskosCombo.addItem(AppState.listakioskos.get(i).getNombreK().toString());   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        correo1Txt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DPITxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rolCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        generoCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        aliasTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        subirBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fechaChooser = new com.toedter.calendar.JDateChooser();
        contra2Txt = new javax.swing.JPasswordField();
        rutaTxt = new javax.swing.JTextField();
        nacionalCombo = new javax.swing.JComboBox<>();
        kioskosCombo = new javax.swing.JComboBox<>();
        kioskoLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fotoLbl = new javax.swing.JLabel();
        contra1Txt = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Regístrate");

        jLabel2.setText("Correo electrónico");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Reingresar contraseña");

        jLabel7.setText("DPI");

        jLabel8.setText("Rol");

        rolCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario Individual", "Usuario Empresarial", "Kiosco" }));
        rolCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rolComboItemStateChanged(evt);
            }
        });
        rolCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolComboActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha de nacimiento");

        jLabel10.setText("Género");

        generoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", "OTRO" }));

        jLabel11.setText("Nacionalidad");

        jLabel12.setText("Sobrenombre");

        jLabel13.setText("Teléfono");

        subirBtn.setBackground(new java.awt.Color(153, 204, 255));
        subirBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subirBtn.setText("SUBIR");
        subirBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));
        subirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("REGISTRAR");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("REGRESAR AL LOGIN");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        rutaTxt.setText("SIN FOTO");

        nacionalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "guatemalteco", "mexicano", "salvadoreño", "argentino", "chileno", "peruano", "costarricense", "panameño", "uruguayo", " " }));

        kioskoLbl.setText("Seleccione su Kiosco Asociado");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        fotoLbl.setBackground(new java.awt.Color(153, 204, 255));
        fotoLbl.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(correo1Txt)
                        .addComponent(DPITxt)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(apellidoTxt)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(rolCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kioskosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kioskoLbl)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(contra1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6)
                                        .addComponent(contra2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(generoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(nacionalCombo, 0, 155, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(aliasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jLabel13)
                                    .addComponent(telefonoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(subirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(rutaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correo1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(8, 8, 8)
                                .addComponent(generoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nacionalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aliasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(contra2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contra1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DPITxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rolCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kioskoLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kioskosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109)
                        .addComponent(rutaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        
        String contra=contra1Txt.getText();
        String pass2 = contra2Txt.getText();
        String correo=correo1Txt.getText();
        
            
       
        if(correo1Txt.getText().length()==0 || nombreTxt.getText().isEmpty() ||apellidoTxt.getText().isEmpty() || contra1Txt.getText().isEmpty()|| contra2Txt.getText().isEmpty()|| DPITxt.getText().isEmpty()|| aliasTxt.getText().isEmpty() || telefonoTxt.getText().isEmpty() /*||  rutaTxt.getText().isEmpty()*/){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        }
        else{
 
            if(contra.equals(pass2)==false){      
            JOptionPane.showMessageDialog(null, "La contraseña ingresada no coincide", "Registro de Usuario", JOptionPane.WARNING_MESSAGE);
            }
        
            else if (contra.equals(pass2)==true){
            
                final int min_mayus=1; // número min de letras mayúsculas 
                final int min_minus=1; // min de letras minúsculas 
                final int min_num=1; // min de numeros
                final int especial=1; // caracteres espciales

                //contadores de caracteres
                int countmayus=0; 
                int countminus=0; 
                int countnum=0; 
                int countespecial=0; 

                for (int i=0; i < contra.length(); i++ ) {
                    char c = contra.charAt(i);
                    if(Character.isUpperCase(c)) 
                        countmayus++;
                    else if(Character.isLowerCase(c)) 
                        countminus++;
                    else if(Character.isDigit(c)) 
                        countnum++;     
                    if(c>=33&&c<=46||c==64){
                        countespecial++;
                    }
                }
             
            
            
                if (countmayus>= min_mayus && countminus>= min_minus && countnum>= min_num && countespecial>= especial){
                    
                    boolean error=false;
                    for (int k=0;k<AppState.listausuarios.size();k++){
                        if (correo.equals(AppState.listausuarios.get(k).getCorreo())==true){      
                            JOptionPane.showMessageDialog(null, "El correo ingresado ya se encuentra registrado", "Usuario Existente", JOptionPane.WARNING_MESSAGE); 
                            error = true;
                            break;
                        }
                    } 
        
                    String nombre=nombreTxt.getText();
                    String apellido=apellidoTxt.getText();
                    Usuario addusuario = new Usuario();
                    long DPI= Long.parseLong(DPITxt.getText());
                    String fecha= fechaChooser.getDate().toString();
                    String genero= generoCombo.getSelectedItem().toString();
                    String nacionalidad = nacionalCombo.getSelectedItem().toString();
                    String sobrenombre = aliasTxt.getText();
                    long telefono= Long.parseLong(telefonoTxt.getText());
                    String rol= rolCombo.getSelectedItem().toString();
                    
                    ImageIcon foto = new ImageIcon(rutaTxt.getText());
                    
                    if (error==true){
                        JOptionPane.showMessageDialog(null, "Asegurese de no estar ingresando un correo con cuenta existente", "Correo inválido", JOptionPane.WARNING_MESSAGE);
                    }else{
                        if(rolCombo.getSelectedIndex()==2){
                            String rolkiosko= kioskosCombo.getSelectedItem().toString();
                            addusuario.setCorreo(correo);
                            addusuario.setNombre(nombre);
                            addusuario.setApellido(apellido);
                            addusuario.setContraseña(contra);
                            addusuario.setDPI(DPI);
                            addusuario.setFecha(fecha);
                            addusuario.setGenero(genero);
                            addusuario.setNacionalidad(nacionalidad);
                            addusuario.setSobrenombre(sobrenombre);
                            addusuario.setTelefono(telefono);
                            addusuario.setRol(rolkiosko);
                            addusuario.setFoto(foto);
                            AppState.listausuarios.add(addusuario);
                            for(int i = 0; i< AppState.listausuarios.size(); i++){ 
                                System.out.println(AppState.listausuarios.get(i).getCorreo()+AppState.listausuarios.get(i).getNombre()+AppState.listausuarios.get(i).getApellido()+AppState.listausuarios.get(i).getContraseña()+AppState.listausuarios.get(i).getDPI()+AppState.listausuarios.get(i).getFecha()+AppState.listausuarios.get(i).getGenero()+AppState.listausuarios.get(i).getNacionalidad()+AppState.listausuarios.get(i).getSobrenombre()+AppState.listausuarios.get(i).getTelefono()+AppState.listausuarios.get(i).getRol()+AppState.listausuarios.get(i).getFoto());  //se invoca el método toString de la clase Coche  
                            }
                           JOptionPane.showMessageDialog(null, "Usuario Registrado Correctamente", "Registro de Usuario", JOptionPane.INFORMATION_MESSAGE);
                           correo1Txt.setText(null);nombreTxt.setText(null);apellidoTxt.setText(null);
                           DPITxt.setText(null);aliasTxt.setText(null);telefonoTxt.setText(null);rutaTxt.setText("SIN FOTO");
                           contra1Txt.setText(null);contra2Txt.setText(null);
                        }else if (rolCombo.getSelectedIndex()==0 || rolCombo.getSelectedIndex()==1) {
                            addusuario.setCorreo(correo);
                            addusuario.setNombre(nombre);
                            addusuario.setApellido(apellido);
                            addusuario.setContraseña(contra);
                            addusuario.setDPI(DPI);
                            addusuario.setFecha(fecha);
                            addusuario.setGenero(genero);
                            addusuario.setNacionalidad(nacionalidad);
                            addusuario.setSobrenombre(sobrenombre);
                            addusuario.setTelefono(telefono);
                            addusuario.setRol(rol);
                            addusuario.setFoto(foto);
                            AppState.listausuarios.add(addusuario);
                            for(int i = 0; i< AppState.listausuarios.size(); i++){ 
                                System.out.println(AppState.listausuarios.get(i).getCorreo()+AppState.listausuarios.get(i).getNombre()+AppState.listausuarios.get(i).getApellido()+AppState.listausuarios.get(i).getContraseña()+AppState.listausuarios.get(i).getDPI()+AppState.listausuarios.get(i).getFecha()+AppState.listausuarios.get(i).getGenero()+AppState.listausuarios.get(i).getNacionalidad()+AppState.listausuarios.get(i).getSobrenombre()+AppState.listausuarios.get(i).getTelefono()+AppState.listausuarios.get(i).getRol()+AppState.listausuarios.get(i).getFoto());  //se invoca el método toString de la clase Coche  
                            }
                           JOptionPane.showMessageDialog(null, "Usuario Registrado Correctamente", "Registro de Usuario", JOptionPane.INFORMATION_MESSAGE);
                           correo1Txt.setText(null);nombreTxt.setText(null);apellidoTxt.setText(null);
                           DPITxt.setText(null);aliasTxt.setText(null);telefonoTxt.setText(null);rutaTxt.setText("SIN FOTO");
                           contra1Txt.setText(null);contra2Txt.setText(null);
                        }
                        
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "La contraseña debe de estar conformada por:\n" +
                    "1. Letras mayúsculas\n" +
                    "2. Letras minúsculas\n" +
                    "3. Números\n" +
                    "4. Caracteres especiales (Ej. #,%,&,_,etc.)", "Requisitos de Contraseña", JOptionPane.WARNING_MESSAGE);
                }
            } 
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void subirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        int ventana= archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION){
            File file= archivo.getSelectedFile();
            rutaTxt.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(rutaTxt.getText());
            foto = foto.getScaledInstance(fotoLbl.getWidth(), fotoLbl.getHeight(), Image.SCALE_DEFAULT);
            fotoLbl.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_subirBtnActionPerformed

    private void rolComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolComboActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_rolComboActionPerformed

    private void rolComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rolComboItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()== ItemEvent.SELECTED){ 
            if(this.rolCombo.getSelectedIndex()==0){ 
                kioskosCombo.setVisible(false);
                kioskoLbl.setVisible(false);
            }else if(this.rolCombo.getSelectedIndex()==1){ 
                kioskosCombo.setVisible(false);
                kioskoLbl.setVisible(false);
            }
            else if(this.rolCombo.getSelectedIndex()==2){ 
                kioskosCombo.setVisible(true);
                kioskoLbl.setVisible(true);
            }
         }       
    }//GEN-LAST:event_rolComboItemStateChanged
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPITxt;
    private javax.swing.JTextField aliasTxt;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JTextField contra1Txt;
    private javax.swing.JPasswordField contra2Txt;
    private javax.swing.JTextField correo1Txt;
    private com.toedter.calendar.JDateChooser fechaChooser;
    private javax.swing.JLabel fotoLbl;
    private javax.swing.JComboBox<String> generoCombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kioskoLbl;
    private javax.swing.JComboBox<String> kioskosCombo;
    private javax.swing.JComboBox<String> nacionalCombo;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JComboBox<String> rolCombo;
    private javax.swing.JTextField rutaTxt;
    private javax.swing.JButton subirBtn;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables
}
